////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.5477
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CoreService.Domain
//{
//    using System.Runtime.Serialization;

//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name = "LdapUserInfo", Namespace = "http://schemas.datacontract.org/2004/07/CoreService.Domain")]
//    public partial class LdapUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
//    {

//        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

//        private string BusinessCategoryField;

//        private string CityField;

//        private string CnField;

//        private string CountryField;

//        private string DepartmentNumberField;

//        private string DisplayNameField;

//        private string DistinguishedNameField;

//        private string DnField;

//        private string[] DsCorePropagationDataField;

//        private string EmployeeNumberField;

//        private string EmployeeTypeField;

//        private string[] ErrorMessagesField;

//        private string FacsimileTelephoneNumberField;

//        private string GivenNameField;

//        private bool IsAccountNotActivatedField;

//        private bool IsInvalidPasswordField;

//        private bool IsPasswordExpiredField;

//        private bool IsValidUserField;

//        private bool IsValidUserIdField;

//        private string MailField;

//        private string ManagerField;

//        private string NameField;

//        private string OField;

//        private string ObjectCategoryField;

//        private string[] ObjectClassField;

//        private string OtherMailBoxField;

//        private string[] OuField;

//        private string PostalCodeField;

//        private string SamAccountNameField;

//        private string SnField;

//        private string StateField;

//        private string[] StreetsField;

//        private string TelephoneNumberField;

//        private string TitleField;

//        private string TxtADuserPrincipalNameField;

//        private string[] TxtARPGroupField;

//        private string TxtAuthenticationMethodField;

//        private string TxtBUCodeField;

//        private string TxtBadgeNumberField;

//        private string TxtBellP2PaccountField;

//        private string TxtBellSAPUniqueIdField;

//        private string[] TxtBellSAPVendorCodesField;

//        private string TxtBellSelectedAccountField;

//        private string TxtBellUserLocationField;

//        private string TxtBellVistaCustomerCodeField;

//        private string TxtCommonIdField;

//        private string TxtCompanyCodeField;

//        private string TxtCostCenterField;

//        private string TxtDefaultBusinessUnitField;

//        private string TxtDomainField;

//        private string TxtENEField;

//        private string TxtExternalMailField;

//        private string TxtFNFField;

//        private string TxtIdTypeField;

//        private string[] TxtIdentitiesField;

//        private string TxtJobFunctionField;

//        private string TxtManagerFlagField;

//        private string[] TxtOtherBusinessUnitField;

//        private string TxtPersonTypeField;

//        private string[] TxtPortalDomainField;

//        private string TxtRegulatoryRegionField;

//        private string TxtSelectedBusinessUnitField;

//        private string TxtSupervisorIdField;

//        private string TxtTopBusinessUnitField;

//        private string TxtUPNField;

//        private string TxtUsPersonField;

//        private string[] TxtVendorCodesField;

//        private string TxtWorkLocationField;

//        private string USnChangedField;

//        private string USnCreatedField;

//        private string[] UidsField;

//        private string UserPrincipalNameField;

//        private string WhenChangedField;

//        private string WhenCreatedField;

//        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
//        {
//            get
//            {
//                return this.extensionDataField;
//            }
//            set
//            {
//                this.extensionDataField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string BusinessCategory
//        {
//            get
//            {
//                return this.BusinessCategoryField;
//            }
//            set
//            {
//                this.BusinessCategoryField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string City
//        {
//            get
//            {
//                return this.CityField;
//            }
//            set
//            {
//                this.CityField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Cn
//        {
//            get
//            {
//                return this.CnField;
//            }
//            set
//            {
//                this.CnField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Country
//        {
//            get
//            {
//                return this.CountryField;
//            }
//            set
//            {
//                this.CountryField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string DepartmentNumber
//        {
//            get
//            {
//                return this.DepartmentNumberField;
//            }
//            set
//            {
//                this.DepartmentNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string DisplayName
//        {
//            get
//            {
//                return this.DisplayNameField;
//            }
//            set
//            {
//                this.DisplayNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string DistinguishedName
//        {
//            get
//            {
//                return this.DistinguishedNameField;
//            }
//            set
//            {
//                this.DistinguishedNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Dn
//        {
//            get
//            {
//                return this.DnField;
//            }
//            set
//            {
//                this.DnField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] DsCorePropagationData
//        {
//            get
//            {
//                return this.DsCorePropagationDataField;
//            }
//            set
//            {
//                this.DsCorePropagationDataField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string EmployeeNumber
//        {
//            get
//            {
//                return this.EmployeeNumberField;
//            }
//            set
//            {
//                this.EmployeeNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string EmployeeType
//        {
//            get
//            {
//                return this.EmployeeTypeField;
//            }
//            set
//            {
//                this.EmployeeTypeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] ErrorMessages
//        {
//            get
//            {
//                return this.ErrorMessagesField;
//            }
//            set
//            {
//                this.ErrorMessagesField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string FacsimileTelephoneNumber
//        {
//            get
//            {
//                return this.FacsimileTelephoneNumberField;
//            }
//            set
//            {
//                this.FacsimileTelephoneNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string GivenName
//        {
//            get
//            {
//                return this.GivenNameField;
//            }
//            set
//            {
//                this.GivenNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public bool IsAccountNotActivated
//        {
//            get
//            {
//                return this.IsAccountNotActivatedField;
//            }
//            set
//            {
//                this.IsAccountNotActivatedField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public bool IsInvalidPassword
//        {
//            get
//            {
//                return this.IsInvalidPasswordField;
//            }
//            set
//            {
//                this.IsInvalidPasswordField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public bool IsPasswordExpired
//        {
//            get
//            {
//                return this.IsPasswordExpiredField;
//            }
//            set
//            {
//                this.IsPasswordExpiredField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public bool IsValidUser
//        {
//            get
//            {
//                return this.IsValidUserField;
//            }
//            set
//            {
//                this.IsValidUserField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public bool IsValidUserId
//        {
//            get
//            {
//                return this.IsValidUserIdField;
//            }
//            set
//            {
//                this.IsValidUserIdField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Mail
//        {
//            get
//            {
//                return this.MailField;
//            }
//            set
//            {
//                this.MailField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Manager
//        {
//            get
//            {
//                return this.ManagerField;
//            }
//            set
//            {
//                this.ManagerField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Name
//        {
//            get
//            {
//                return this.NameField;
//            }
//            set
//            {
//                this.NameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string O
//        {
//            get
//            {
//                return this.OField;
//            }
//            set
//            {
//                this.OField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string ObjectCategory
//        {
//            get
//            {
//                return this.ObjectCategoryField;
//            }
//            set
//            {
//                this.ObjectCategoryField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] ObjectClass
//        {
//            get
//            {
//                return this.ObjectClassField;
//            }
//            set
//            {
//                this.ObjectClassField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string OtherMailBox
//        {
//            get
//            {
//                return this.OtherMailBoxField;
//            }
//            set
//            {
//                this.OtherMailBoxField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] Ou
//        {
//            get
//            {
//                return this.OuField;
//            }
//            set
//            {
//                this.OuField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string PostalCode
//        {
//            get
//            {
//                return this.PostalCodeField;
//            }
//            set
//            {
//                this.PostalCodeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SamAccountName
//        {
//            get
//            {
//                return this.SamAccountNameField;
//            }
//            set
//            {
//                this.SamAccountNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Sn
//        {
//            get
//            {
//                return this.SnField;
//            }
//            set
//            {
//                this.SnField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string State
//        {
//            get
//            {
//                return this.StateField;
//            }
//            set
//            {
//                this.StateField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] Streets
//        {
//            get
//            {
//                return this.StreetsField;
//            }
//            set
//            {
//                this.StreetsField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TelephoneNumber
//        {
//            get
//            {
//                return this.TelephoneNumberField;
//            }
//            set
//            {
//                this.TelephoneNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Title
//        {
//            get
//            {
//                return this.TitleField;
//            }
//            set
//            {
//                this.TitleField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtADuserPrincipalName
//        {
//            get
//            {
//                return this.TxtADuserPrincipalNameField;
//            }
//            set
//            {
//                this.TxtADuserPrincipalNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtARPGroup
//        {
//            get
//            {
//                return this.TxtARPGroupField;
//            }
//            set
//            {
//                this.TxtARPGroupField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtAuthenticationMethod
//        {
//            get
//            {
//                return this.TxtAuthenticationMethodField;
//            }
//            set
//            {
//                this.TxtAuthenticationMethodField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBUCode
//        {
//            get
//            {
//                return this.TxtBUCodeField;
//            }
//            set
//            {
//                this.TxtBUCodeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBadgeNumber
//        {
//            get
//            {
//                return this.TxtBadgeNumberField;
//            }
//            set
//            {
//                this.TxtBadgeNumberField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBellP2Paccount
//        {
//            get
//            {
//                return this.TxtBellP2PaccountField;
//            }
//            set
//            {
//                this.TxtBellP2PaccountField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBellSAPUniqueId
//        {
//            get
//            {
//                return this.TxtBellSAPUniqueIdField;
//            }
//            set
//            {
//                this.TxtBellSAPUniqueIdField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtBellSAPVendorCodes
//        {
//            get
//            {
//                return this.TxtBellSAPVendorCodesField;
//            }
//            set
//            {
//                this.TxtBellSAPVendorCodesField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBellSelectedAccount
//        {
//            get
//            {
//                return this.TxtBellSelectedAccountField;
//            }
//            set
//            {
//                this.TxtBellSelectedAccountField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBellUserLocation
//        {
//            get
//            {
//                return this.TxtBellUserLocationField;
//            }
//            set
//            {
//                this.TxtBellUserLocationField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtBellVistaCustomerCode
//        {
//            get
//            {
//                return this.TxtBellVistaCustomerCodeField;
//            }
//            set
//            {
//                this.TxtBellVistaCustomerCodeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtCommonId
//        {
//            get
//            {
//                return this.TxtCommonIdField;
//            }
//            set
//            {
//                this.TxtCommonIdField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtCompanyCode
//        {
//            get
//            {
//                return this.TxtCompanyCodeField;
//            }
//            set
//            {
//                this.TxtCompanyCodeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtCostCenter
//        {
//            get
//            {
//                return this.TxtCostCenterField;
//            }
//            set
//            {
//                this.TxtCostCenterField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtDefaultBusinessUnit
//        {
//            get
//            {
//                return this.TxtDefaultBusinessUnitField;
//            }
//            set
//            {
//                this.TxtDefaultBusinessUnitField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtDomain
//        {
//            get
//            {
//                return this.TxtDomainField;
//            }
//            set
//            {
//                this.TxtDomainField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtENE
//        {
//            get
//            {
//                return this.TxtENEField;
//            }
//            set
//            {
//                this.TxtENEField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtExternalMail
//        {
//            get
//            {
//                return this.TxtExternalMailField;
//            }
//            set
//            {
//                this.TxtExternalMailField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtFNF
//        {
//            get
//            {
//                return this.TxtFNFField;
//            }
//            set
//            {
//                this.TxtFNFField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtIdType
//        {
//            get
//            {
//                return this.TxtIdTypeField;
//            }
//            set
//            {
//                this.TxtIdTypeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtIdentities
//        {
//            get
//            {
//                return this.TxtIdentitiesField;
//            }
//            set
//            {
//                this.TxtIdentitiesField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtJobFunction
//        {
//            get
//            {
//                return this.TxtJobFunctionField;
//            }
//            set
//            {
//                this.TxtJobFunctionField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtManagerFlag
//        {
//            get
//            {
//                return this.TxtManagerFlagField;
//            }
//            set
//            {
//                this.TxtManagerFlagField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtOtherBusinessUnit
//        {
//            get
//            {
//                return this.TxtOtherBusinessUnitField;
//            }
//            set
//            {
//                this.TxtOtherBusinessUnitField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtPersonType
//        {
//            get
//            {
//                return this.TxtPersonTypeField;
//            }
//            set
//            {
//                this.TxtPersonTypeField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtPortalDomain
//        {
//            get
//            {
//                return this.TxtPortalDomainField;
//            }
//            set
//            {
//                this.TxtPortalDomainField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtRegulatoryRegion
//        {
//            get
//            {
//                return this.TxtRegulatoryRegionField;
//            }
//            set
//            {
//                this.TxtRegulatoryRegionField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtSelectedBusinessUnit
//        {
//            get
//            {
//                return this.TxtSelectedBusinessUnitField;
//            }
//            set
//            {
//                this.TxtSelectedBusinessUnitField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtSupervisorId
//        {
//            get
//            {
//                return this.TxtSupervisorIdField;
//            }
//            set
//            {
//                this.TxtSupervisorIdField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtTopBusinessUnit
//        {
//            get
//            {
//                return this.TxtTopBusinessUnitField;
//            }
//            set
//            {
//                this.TxtTopBusinessUnitField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtUPN
//        {
//            get
//            {
//                return this.TxtUPNField;
//            }
//            set
//            {
//                this.TxtUPNField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtUsPerson
//        {
//            get
//            {
//                return this.TxtUsPersonField;
//            }
//            set
//            {
//                this.TxtUsPersonField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] TxtVendorCodes
//        {
//            get
//            {
//                return this.TxtVendorCodesField;
//            }
//            set
//            {
//                this.TxtVendorCodesField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string TxtWorkLocation
//        {
//            get
//            {
//                return this.TxtWorkLocationField;
//            }
//            set
//            {
//                this.TxtWorkLocationField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string USnChanged
//        {
//            get
//            {
//                return this.USnChangedField;
//            }
//            set
//            {
//                this.USnChangedField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string USnCreated
//        {
//            get
//            {
//                return this.USnCreatedField;
//            }
//            set
//            {
//                this.USnCreatedField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string[] Uids
//        {
//            get
//            {
//                return this.UidsField;
//            }
//            set
//            {
//                this.UidsField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string UserPrincipalName
//        {
//            get
//            {
//                return this.UserPrincipalNameField;
//            }
//            set
//            {
//                this.UserPrincipalNameField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string WhenChanged
//        {
//            get
//            {
//                return this.WhenChangedField;
//            }
//            set
//            {
//                this.WhenChangedField = value;
//            }
//        }

//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string WhenCreated
//        {
//            get
//            {
//                return this.WhenCreatedField;
//            }
//            set
//            {
//                this.WhenCreatedField = value;
//            }
//        }
//    }
//}


//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
//[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ILdapAuthenticationService")]
//public interface ILdapAuthenticationService
//{

//    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILdapAuthenticationService/Authentication", ReplyAction = "http://tempuri.org/ILdapAuthenticationService/AuthenticationResponse")]
//    CoreService.Domain.LdapUserInfo Authentication(string ldapUserId, string ldapUserPw);

//    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILdapAuthenticationService/SearchLdap", ReplyAction = "http://tempuri.org/ILdapAuthenticationService/SearchLdapResponse")]
//    CoreService.Domain.LdapUserInfo SearchLdap(string employeeNumber, string emailAddress, string networkLoginId);
//}

//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
//public interface ILdapAuthenticationServiceChannel : ILdapAuthenticationService, System.ServiceModel.IClientChannel
//{
//}

//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
//public partial class LdapAuthenticationServiceClient : System.ServiceModel.ClientBase<ILdapAuthenticationService>, ILdapAuthenticationService
//{

//    public LdapAuthenticationServiceClient()
//    {
//    }

//    public LdapAuthenticationServiceClient(string endpointConfigurationName) :
//            base(endpointConfigurationName)
//    {
//    }

//    public LdapAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) :
//            base(endpointConfigurationName, remoteAddress)
//    {
//    }

//    public LdapAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
//            base(endpointConfigurationName, remoteAddress)
//    {
//    }

//    public LdapAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
//            base(binding, remoteAddress)
//    {
//    }

//    public CoreService.Domain.LdapUserInfo Authentication(string ldapUserId, string ldapUserPw)
//    {
//        return base.Channel.Authentication(ldapUserId, ldapUserPw);
//    }

//    public CoreService.Domain.LdapUserInfo SearchLdap(string employeeNumber, string emailAddress, string networkLoginId)
//    {
//        return base.Channel.SearchLdap(employeeNumber, emailAddress, networkLoginId);
//    }
//}
